let permissions = new Map()
permissions.set('RETRIEVE_USER', 'retrieve.user')
permissions.set('RETRIEVE_ALL_USERS', 'retrieve.all.users')
permissions.set('CREATE_USER', 'create.user')
permissions.set('UPDATE_USER', 'update.user')
permissions.set('DELETE_USER', 'delete.user')
permissions.set('RETRIEVE_ACCOUNT', 'retrieve.account')
permissions.set('RETRIEVE_ALL_ACCOUNTS', 'retrieve.all.accounts')
permissions.set('CREATE_ACCOUNT', 'create.account')
permissions.set('UPDATE_ACCOUNT', 'update.account')
permissions.set('DELETE_ACCOUNT', 'delete.account')
permissions.set('RETRIEVE_BANKACCOUNT', 'retrieve.bankAccount')
permissions.set('RETRIEVE_ALL_BANKACCOUNTS', 'retrieve.all.bankaccounts')
permissions.set('CREATE_BANKACCOUNT', 'create.bankAccount')
permissions.set('UPDATE_BANKACCOUNT', 'update.bankAccount')
permissions.set('DELETE_BANKACCOUNT', 'delete.bankAccount')
permissions.set('RETRIEVE_COMPANY', 'retrieve.company')
permissions.set('RETRIEVE_ALL_COMPANIES', 'retrieve.all.companies')
permissions.set('CREATE_COMPANY', 'create.company')
permissions.set('UPDATE_COMPANY', 'update.company')
permissions.set('DELETE_COMPANY', 'delete.company')
permissions.set('RETRIEVE_EMPLOYEE', 'retrieve.employee')
permissions.set('RETRIEVE_ALL_EMPLOYEES', 'retrieve.all.employees')
permissions.set('CREATE_EMPLOYEE', 'create.employee')
permissions.set('UPDATE_EMPLOYEE', 'update.employee')
permissions.set('DELETE_EMPLOYEE', 'delete.employee')
permissions.set('RETRIEVE_BANK', 'retrieve.bank')
permissions.set('RETRIEVE_ALL_BANKS', 'retrieve.all.banks')
permissions.set('CREATE_BANK', 'create.bank')
permissions.set('UPDATE_BANK', 'update.bank')
permissions.set('DELETE_BANK', 'delete.bank')
permissions.set('RETRIEVE_TAX', 'retrieve.tax.type')
permissions.set('RETRIEVE_ALL_TAXES', 'retrieve.all.tax.types')
permissions.set('CREATE_TAX', 'create.tax.type')
permissions.set('UPDATE_TAX', 'update.tax.type')
permissions.set('DELETE_TAX', 'delete.tax.type')
permissions.set('RETRIEVE_INVOICE', 'retrieve.invoice')
permissions.set('RETRIEVE_ALL_INVOICES', 'retrieve.all.invoices')
permissions.set('CREATE_INVOICE', 'create.invoice')
permissions.set('UPDATE_INVOICE', 'update.invoice')
permissions.set('DELETE_INVOICE', 'delete.invoice')
permissions.set('RETRIEVE_TAXITEM', 'retrieve.taxItem')
permissions.set('RETRIEVE_ALL_TAXITEMS', 'retrieve.all.taxitems')
permissions.set('CREATE_TAXITEM', 'create.taxItem')
permissions.set('UPDATE_TAXITEM', 'update.taxItem')
permissions.set('DELETE_TAXITEM', 'delete.taxItem')
permissions.set('RETRIEVE_TRANSACTION', 'retrieve.transaction')
permissions.set('RETRIEVE_ALL_TRANSACTIONS', 'retrieve.all.transactions')
permissions.set('CREATE_TRANSACTION', 'create.transaction')
permissions.set('UPDATE_TRANSACTION', 'update.transaction')
permissions.set('DELETE_TRANSACTION', 'delete.transaction')

permissions.set('DASHBOARD', 'dashboard')

let roles = new Map()
roles.set('ADMIN','admin')
roles.set('OPERATOR','operator')
roles.set('CLIENT_OPERATOR','client_operator')
roles.set('CLIENT_EXECUTIVE','client_executive')

let transactionStatus = new Map()
transactionStatus.set('OPEN','open')
transactionStatus.set('ONGOING','ongoing')
transactionStatus.set('CLOSED','closed')

let invoiceStatus = new Map()
invoiceStatus.set('ACTIVE','active')
invoiceStatus.set('PAID','paid')
invoiceStatus.set('REPORTED','reported')
invoiceStatus.set('TENTATIVE_PAID', 'tentative_paid') 
invoiceStatus.set('OVERDUE','overdue')

export default {
    roles,
    permissions,
    transactionStatus,
    invoiceStatus,
}